spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: higuys
    hikari:
      minimum-idle: 3
      maximum-pool-size: 15
      connection-test-query: SELECT 1
mybatis:
  mapper-locations: classpath:mapping/*.xml
