spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    username: root
    password: higuys
    hikari:
      minimum-idle: 3
      maximum-pool-size: 15
      connection-test-query: SELECT 1
  redis:
    port: 6379
    host: 127.0.0.1
mybatis:
  configuration:
    map-underscore-to-camel-case: true
server:
  port: 8080